spring:
  application:
    name: epharmacy_backend
  datasource:
    url: jdbc:mysql://localhost:3306/epharmacy_db
    username: root
    password: saurabh123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8000